# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'O+')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_App.Address')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=1)),
                ('age', models.CharField(max_length=2)),
                ('contact', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_App.Address')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_App.BloodGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=512)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_App.RegisteredUser')),
            ],
        ),
        migrations.AddField(
            model_name='bloodpouch',
            name='donated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_App.RegisteredUser'),
        ),
    ]
