# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_App', '0003_bloodpouch_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='age',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='dob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodpouch',
            name='blood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_App.BloodGroup'),
        ),
    ]
