# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_App', '0003_auto_20170404_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pin',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registereduser',
            name='contact',
            field=models.CharField(default=None, max_length=13),
            preserve_default=False,
        ),
    ]
