# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_App', '0004_auto_20170408_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpouch',
            name='is_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_pouch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Blood_App.BloodPouch'),
            preserve_default=False,
        ),
    ]
