# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_App', '0004_auto_20170404_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='age',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
