# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_App', '0005_registereduser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='blood_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Blood_App.BloodGroup'),
            preserve_default=False,
        ),
    ]
