# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_App', '0005_auto_20170408_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='quantity_needed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
