# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_App', '0007_bloodpouch_is_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_issued',
            field=models.IntegerField(default=0),
        ),
    ]
