# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_App', '0008_request_is_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpouch',
            name='is_issued',
        ),
    ]
